### ISSUE TITLE
Problems with the bibliography APA7

### ISSUE THREAD

**Issue by JG2021pe** [lx3h/LinguisticsJournals#2]
Hello. When generating the bibliography the indentation is not generated. What should I do? Thanks for your answer.

**Comment by lx3h** [comment]
Sharp eyes! I have not been able to hardcode the indentation needed. Still hoping someone more experienced can give me a hint. The simple work around is highlighting the whole reference list and adjusting the indentation manually. After that, the indentation will stay even if you refresh the reference list.

**Comment by lx3h** [comment]
Also, Ctrl+A in the reference list and then Ctrl+T does the job too.
