### ISSUE TITLE
how 2

### ISSUE THREAD

**Issue by colajohn** [lx3h/LinguisticsJournals#3]
stupid q, how do i take the apa 7 file in the style folder?. just mark all and then ctrl c and paste ctrl v in the folder?

**Comment by lx3h** [comment]
If you only want APA7thEd, then just put the .XSL in the Style folder. You also need to replace the BIBFORM.XML in the Bibliography folder.

Here is what I wrote in the README,

Just place:
			1. the .XSL files you need, and types.xml into the folder %userprofile%\AppData\Roaming\Microsoft\Bibliography\Style
			2. the BIBFORM.XML into the folder C:\Program Files\Microsoft Office\root\Office16\1033\Bibliography then restart Microsoft Word to use the new citation and bibliography styles. (This will need to be reperformed if the desired "Type of Source" under "Insert Citation" is no longer there. That's because MS Word does update this file whenever it detects a change to it.)

**Comment by colajohn** [comment]
a problem: i get unsuportet source type when i use electronic sourc
apa 7: (Unsupported source type (ElectronicSource) for source Utd18.)
while apa 6: (Utdannings direktoratet, 2018)

**Comment by lx3h** [comment]
Electronic Source is there in APA7 but not recommended, because electronic sources can be further categorised into website, tweet, video, etc.
